version: "3.1"
services:
  db:
    image: postgres:12.6
    restart: unless-stopped
    container_name: autotests_cloud-dev-db-container
    hostname: autotests_cloud-dev-db
    environment:
      POSTGRES_DB: autotests_cloud_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    ports:
      - 5432:5432
    networks:
      - localnet
    volumes:
      - autotests_cloud_dev_db_data:/var/lib/postgresql/data
networks:
  localnet:
    driver: bridge
volumes:
  autotests_cloud_dev_db_data: