
    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://selenide.org'", () ->
            open("https://selenide.org"));

        step("Checking that page title is 'Selenide: concise UI tests in Java'", () -> {
            String expectedTitle = "Selenide: concise UI tests in Java";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
